# Generated by Django 3.1 on 2022-02-19 23:44

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('title', models.TextField(verbose_name='書名')),
                ('ISBN', models.TextField(verbose_name='ISBN')),
                ('publisher', models.TextField(verbose_name='發行商')),
                ('author', models.TextField(verbose_name='作者名')),
                ('date', models.TextField(verbose_name='發行日')),
                ('spu_image', models.TextField(verbose_name='圖片網址')),
                ('detail', ckeditor.fields.RichTextField(blank=True, verbose_name='商品介紹')),
                ('orginal_price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='商品原價')),
                ('type', models.IntegerField(verbose_name='書的類別')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
                'db_table': 'df_books',
            },
        ),
        migrations.CreateModel(
            name='Books_sku',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='預售價格')),
                ('file', models.FileField(null=True, upload_to='videos/', verbose_name='商品影片')),
                ('status', models.SmallIntegerField(choices=[(0, '下線'), (1, '上線')], default=1, verbose_name='狀態')),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.books', verbose_name='商品SPU')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'df_books_sku',
            },
        ),
    ]
