# Generated by Django 3.1 on 2022-02-27 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_books_sku_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='all_status',
            field=models.SmallIntegerField(choices=[(0, '下線'), (1, '上線')], default=0, verbose_name='總狀態'),
        ),
    ]
