# Generated by Django 3.1 on 2022-03-20 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_address_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='刪除標記')),
                ('account', models.CharField(max_length=16, verbose_name='帳號密碼')),
                ('holder', models.CharField(max_length=20, verbose_name='持卡人姓名')),
                ('dueday', models.CharField(max_length=4, verbose_name='到期日')),
                ('cvv', models.CharField(max_length=3, verbose_name='cvv')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默認')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='所屬用戶')),
            ],
            options={
                'verbose_name': '銀行帳戶',
                'verbose_name_plural': '銀行帳戶',
                'db_table': 'df_card',
            },
        ),
    ]
