# Generated by Django 3.1 on 2022-02-20 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('addr', models.TextField(verbose_name='地址')),
                ('pay_method', models.SmallIntegerField(choices=[(1, '貨到付款'), (2, '銀行轉帳'), (3, '信用卡/金融卡')], default=3, verbose_name='支付方式')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='總金額')),
                ('transit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='運費')),
                ('order_status', models.SmallIntegerField(choices=[(1, '待支付'), (2, '待發貨'), (3, '待收貨'), (4, '已完成')], default=1, verbose_name='訂單狀態')),
                ('trade_no', models.CharField(default='', max_length=128, verbose_name='支付編號')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用戶')),
            ],
            options={
                'verbose_name': '訂單',
                'verbose_name_plural': '訂單',
                'db_table': 'df_order_info',
            },
        ),
    ]
