# Generated by Django 3.1 on 2022-02-21 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetailinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='删除标记')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.orderinfo', verbose_name='訂單')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.books_sku', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '訂單商品',
                'verbose_name_plural': '訂單商品',
                'db_table': 'df_order_goods',
            },
        ),
    ]
