# Generated by Django 3.1 on 2022-02-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderdetailinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='購買日期'),
        ),
    ]
