# Generated by Django 3.1 on 2022-02-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220222_0644'),
        ('order', '0004_auto_20220222_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.address', verbose_name='地址'),
        ),
    ]
