# Generated by Django 3.1 on 2022-03-22 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20220321_0200'),
        ('order', '0006_auto_20220310_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.card', verbose_name='銀行卡號'),
        ),
    ]
